### ISSUE TITLE
Latest version causing game to crash

### ISSUE THREAD

**Issue by ArcaneInferno** [AtmoOmen/CurrencyTracker#15]
Hi,

I just updated to the latest version and it appear the new version is causing the game to crash.

Looked at the dalamud logs, the recurring message is being printed in the log:

[ERR] [WindowSystem] Error during Draw(): Currency Tracker
System.MissingMethodException: Method not found: 'Void Dalamud.Interface.Utility.ImGuiHelpers.CenterCursorFor(Single)'.
   at CurrencyTracker.Windows.Main.CurrencyListboxToolUI()
   at CurrencyTracker.Windows.Main.CurrencyListboxUI() in /work/repo/CurrencyTracker/Windows/Main/MainCurrencyList.cs:line 12
   at CurrencyTracker.Windows.Main.Draw() in /work/repo/CurrencyTracker/Windows/Main/Main.cs:line 72
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 479

Thanks.

**Comment by AtmoOmen** [comment]
Sorry for causing the crash, i will look into this asap!

**Comment by AtmoOmen** [comment]
1.3.2.2 version has released,
 Pls update to see if the issues are solved

**Comment by ArcaneInferno** [comment]
Just updated it, will report back if there's further issue. otherwise, i'll close the issue if nothing arise after a few days of using it

**Comment by AtmoOmen** [comment]
Since it has been a week and a half and no further feedback has been received, and the version reported to cause game crashes has also been disabled, I will now close this issue.

If you encounter any other issues in the latest version, please open a new issue!
