### ISSUE TITLE
Tiny settings window

### ISSUE THREAD

**Issue by ArcaneInferno** [AtmoOmen/CurrencyTracker#19]
![image](https://github.com/AtmoOmen/CurrencyTracker/assets/144722345/a27ac0cb-2b12-4b81-aa40-ba1b8e38cbd6)

The exception message below generate far too many entries to the log file to even considering to counting how many times it occured.

```
2023-12-29 19:12:59.630 +00:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMy0xMi0yOVQxOToxMjo1OS42MzA1Mjk0KzAwOjAwIiwiSW5mbyI6IlN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleU5vdEZvdW5kRXhjZXB0aW9uOiBUaGUgZ2l2ZW4ga2V5ICdMZXR0ZXJBdHRhY2htZW50cycgd2FzIG5vdCBwcmVzZW50IGluIHRoZSBkaWN0aW9uYXJ5LlxyXG4gICBhdCBDdXJyZW5jeVRyYWNrZXIuV2luZG93cy5TZXR0aW5ncy5Nb2R1bGVDaGVja2JveChUeXBlIHR5cGUsIFN0cmluZyBjaGVja2JveExhYmVsLCBTdHJpbmcgaGVscCkgaW4gL3dvcmsvcmVwby9DdXJyZW5jeVRyYWNrZXIvV2luZG93cy9TZXR0aW5ncy5jczpsaW5lIDI4OVxyXG4gICBhdCBDdXJyZW5jeVRyYWNrZXIuV2luZG93cy5TZXR0aW5ncy5EcmF3KCkgaW4gL3dvcmsvcmVwby9DdXJyZW5jeVRyYWNrZXIvV2luZG93cy9TZXR0aW5ncy5jczpsaW5lIDMzXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3cuRHJhd0ludGVybmFsKERhbGFtdWRDb25maWd1cmF0aW9uIGNvbmZpZ3VyYXRpb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXEludGVyZmFjZVxcV2luZG93aW5nXFxXaW5kb3cuY3M6bGluZSA0NzkiLCJDb250ZXh0IjoiW1dpbmRvd1N5c3RlbV0gRXJyb3IgZHVyaW5nIERyYXcoKTogU2V0dGluZ3MjI0N1cnJlbmN5IFRyYWNrZXIifQ==
2023-12-29 19:12:59.630 +00:00 [ERR] [WindowSystem] Error during Draw(): Settings##Currency Tracker
System.Collections.Generic.KeyNotFoundException: The given key 'LetterAttachments' was not present in the dictionary.
   at CurrencyTracker.Windows.Settings.ModuleCheckbox(Type type, String checkboxLabel, String help) in /work/repo/CurrencyTracker/Windows/Settings.cs:line 289
   at CurrencyTracker.Windows.Settings.Draw() in /work/repo/CurrencyTracker/Windows/Settings.cs:line 33
```

**Comment by AtmoOmen** [comment]
It seems that part of your configurations missed, you can fix this error by mannually adding a ``"LetterAttachments": true,`` item in ``CurrencyTracker.json`` - ``ComponentEnabled``. This file should locate in ``$(appdata)\XIVLauncher\pluginConfigs``

I push a small update to avoid partial configuration loss resulting in overall window drawing failure

**Comment by ArcaneInferno** [comment]
That fixed the issue.

Much appreciated!
